#!/bin/bash
# Quick Setup Script for Auto-Deployment
# Run this once to set up everything

set -e

echo "=============================================="
echo "🚀 Auto-Deployment Setup"
echo "=============================================="
echo ""

cd /home/zeah/.openclaw/workspace/school-ranking-site

# Step 1: Configure Git
echo "Step 1: Configuring Git credential helper..."
git config credential.helper store
echo "✅ Git credential helper set to 'store'"
echo ""

# Step 2: Check credentials
echo "Step 2: Checking Git credentials..."
if [ -f ~/.git-credentials ]; then
    echo "✅ Git credentials file exists"
    echo "   Stored credentials:"
    cat ~/.git-credentials | sed 's/:.*@/ [hidden] @/'
else
    echo "⚠️  No stored credentials found"
    echo ""
    echo "📝 Next steps:"
    echo "   1. Generate GitHub Personal Access Token:"
    echo "      https://github.com/settings/tokens"
    echo "   2. Run a test push to save your token:"
    echo "      cd $(pwd)"
    echo "      echo 'test' > .deploy-test"
    echo "      git add .deploy-test"
    echo "      git commit -m 'Test: Setup auto-deploy'"
    echo "      git push origin main"
    echo ""
    echo "   OR directly create credentials file:"
    echo "      echo 'https://your-username:your-token@github.com' > ~/.git-credentials"
    echo "      chmod 600 ~/.git-credentials"
    echo ""
    
    read -p "Have you set up Git credentials? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Please set up credentials first. See FIRST_PUSH_GUIDE.md for help."
        exit 1
    fi
fi
echo ""

# Step 3: Make scripts executable
echo "Step 3: Making scripts executable..."
chmod +x scripts/auto-post-news.py
chmod +x test-auto-deploy.sh
chmod +x setup-auto-deploy.sh
echo "✅ Scripts are executable"
echo ""

# Step 4: Test the auto-post script (optional)
echo "Step 4: Test auto-post script"
read -p "Do you want to test the news posting script now? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Running test..."
    ./test-auto-deploy.sh
    echo ""
fi

# Step 5: Set up cron jobs
echo "Step 5: Setting up cron jobs..."
echo ""
echo "Run these commands to set up automatic news posting:"
echo ""
echo "  # Morning news (9 AM)"
echo "  openclaw cron add --label \"morning-news\" --schedule \"0 9 * * *\" \\"
echo "    --command \"cd $(pwd) && python3 scripts/auto-post-news.py\" \\"
echo "    --description \"Daily morning news (9 AM)\""
echo ""
echo "  # Evening news (6 PM)"
echo "  openclaw cron add --label \"evening-news\" --schedule \"0 18 * * *\" \\"
echo "    --command \"cd $(pwd) && python3 scripts/auto-post-news.py\" \\"
echo "    --description \"Daily evening news (6 PM)\""
echo ""

read -p "Do you want to set up cron jobs now? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Setting up cron jobs..."
    
    openclaw cron add --label "morning-news" --schedule "0 9 * * *" \
      --command "cd $(pwd) && python3 scripts/auto-post-news.py" \
      --description "Daily morning news (9 AM)"
    
    openclaw cron add --label "evening-news" --schedule "0 18 * * *" \
      --command "cd $(pwd) && python3 scripts/auto-post-news.py" \
      --description "Daily evening news (6 PM)"
    
    echo "✅ Cron jobs created"
    echo ""
    echo "Verify with: openclaw cron list"
    echo ""
fi

# Summary
echo "=============================================="
echo "✅ Setup Complete!"
echo "=============================================="
echo ""
echo "📋 What's been configured:"
echo "  ✅ Git credential helper (store)"
echo "  ✅ Scripts are executable"
echo ""
echo "📅 Scheduled tasks:"
echo "  • Daily at 9:00 AM - Morning news"
echo "  • Daily at 6:00 PM - Evening news"
echo ""
echo "📖 Documentation:"
echo "  • AUTO_DEPLOY_README.md - Complete guide"
echo "  • FIRST_PUSH_GUIDE.md - Git authentication"
echo "  • CRON_SETUP.md - Cron job details"
echo ""
echo "🧪 Test the system:"
echo "  cd $(pwd)"
echo "  ./test-auto-deploy.sh"
echo ""
echo "🎉 Your auto-deployment is ready!"
echo "   From now on, news will be automatically:"
echo "   • Generated by AI"
echo "   • Committed to Git"
echo "   • Pushed to GitHub"
echo "   • Deployed on Vercel"
echo ""
echo "   Completely hands-off! 🚀"
echo ""
